// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiw15ul5T95Ekej6P3SH8a5qn3hxPVi7k',
    appId: '1:232322109882:web:6ef88a27c830db69eb8d83',
    messagingSenderId: '232322109882',
    projectId: 'learnly-f6e2d',
    authDomain: 'learnly-f6e2d.firebaseapp.com',
    storageBucket: 'learnly-f6e2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe75K12bLbENW7Nxm1cmNHe8dQ7jAolQY',
    appId: '1:232322109882:android:352fbf715f1ceaabeb8d83',
    messagingSenderId: '232322109882',
    projectId: 'learnly-f6e2d',
    storageBucket: 'learnly-f6e2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0KL7ITsgWoD40FnL1HwEgANRgjXqFwkM',
    appId: '1:232322109882:ios:0bb1655890fe3b60eb8d83',
    messagingSenderId: '232322109882',
    projectId: 'learnly-f6e2d',
    storageBucket: 'learnly-f6e2d.firebasestorage.app',
    iosBundleId: 'com.example.learnly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0KL7ITsgWoD40FnL1HwEgANRgjXqFwkM',
    appId: '1:232322109882:ios:0bb1655890fe3b60eb8d83',
    messagingSenderId: '232322109882',
    projectId: 'learnly-f6e2d',
    storageBucket: 'learnly-f6e2d.firebasestorage.app',
    iosBundleId: 'com.example.learnly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiw15ul5T95Ekej6P3SH8a5qn3hxPVi7k',
    appId: '1:232322109882:web:a023ff53ef326b02eb8d83',
    messagingSenderId: '232322109882',
    projectId: 'learnly-f6e2d',
    authDomain: 'learnly-f6e2d.firebaseapp.com',
    storageBucket: 'learnly-f6e2d.firebasestorage.app',
  );
}
